### ISSUE TITLE
How to build rectangle box for MD wth YAMACS?

### ISSUE THREAD

**Issue by Tangbbmc** [YAMACS-SML/YAMACS#12]
The protein I studied is a rectangle. I want to place it a rectangle box for MD. But YAMACS only provides a cubic box for selection.

**Comment by YAMACS-SML** [comment]
Hello Tangbbmc,
Thanks for using YAMACS. Your feedback is important to improve the effectiveness of YAMACS. The YAMACS plugins are written by considering the capabilities of YASARA and GROMACS. Unfortunately, YASARA supports only cubic and dodecahedron simulation cell for MD. That is why you can not use the rectangle box for MD in YAMACS.
